### ISSUE TITLE
Support iFrames

### ISSUE THREAD

**Issue by dwsmart** [AVGP/dom2html#3]
It's perhaps outside the scope of this, but adding iframe support too seems useful.

This added to subtree.js on line 46 seems to do that job.

`// if it's an iframe, use that...
    if(nodeLike.contentDocument && nodeLike.contentDocument.children.length > 0) {
		nodeLike.contentDocument.children
      .map(child => this.constructSubtreeForNode(document, child, nodeCallback))
      .forEach(child => {
        elem.appendChild(child)
			return elem;
      });
    }`

**Comment by AVGP** [comment]
Sounds like a use case to me. I would suggest you try to make that change and send a pull request?

**Comment by AVGP** [comment]
I'm moving this repository over to github.com/googlechromelabs/dom2html - I recreated your issue there as https://github.com/googlechromelabs/dom2html/issues/3. 

Feel free to assign the issue to yourself and would you mind reopening the pull request against the new repository?
